### ISSUE TITLE
receiving 403: Forbidden error codes when trying to load etf

### ISSUE THREAD

**Issue by msmith6307** [JakubPluta/pyetf#23]
started receiving 403 errors over the last two days when trying to load etf data
was previously working
updated to etfpy 1.0.20 but still seeing the issue.
using - Python 3.11.5
>>> from etfpy import ETF, load_etf, get_available_etfs_list
>>> etfs = get_available_etfs_list()
>>> etfs [works did not copy output here]
>>> spy = ETF("SPY")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\etf.py", line 19, in __init__
    super().__init__(ticker)
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\client\etf_client.py", line 55, in __init__
    self._soup = self._make_soup_request()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\client\etf_client.py", line 84, in _make_soup_request
    raise Exception(f"response {response.status_code}: {response.reason}")
Exception: response 403: Forbidden
>>> spy.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spy' is not defined
>>> vwo = load_etf('VWO')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\etf.py", line 353, in load_etf
    return ETF(etf)
           ^^^^^^^^
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\etf.py", line 19, in __init__
    super().__init__(ticker)
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\client\etf_client.py", line 55, in __init__
    self._soup = self._make_soup_request()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\msmit\anaconda3\Lib\site-packages\etfpy\client\etf_client.py", line 84, in _make_soup_request
    raise Exception(f"response {response.status_code}: {response.reason}")
Exception: response 403: Forbidden

**Comment by tavaskor** [comment]
> updated to etfpy 1.0.20 but still seeing the issue.

This issue also applies to other programmatic access to etfdb ; e.g., https://github.com/lvxhnat/pyetfdb-scraper

**Comment by npreiser** [comment]
same here ,  worked a about 10 days ago for me, bummer,

**Comment by tchenard** [comment]
Any update on this or know of a workaround?  I am also getting the 403 Forbidden error

**Comment by horlatunjiey** [comment]
Has anyone found a solution to the 403: Forbidden error? I've been grappling with this challenge for over three weeks now.

**Comment by msmith6307** [comment]
Ended up using headless selenium to get the data

**Comment by Cerebex** [comment]
> Ended up using headless selenium to get the data

Can you share this code? I have attempted as-well with selenium headless but it always seems to not fully load the page in headless mode.

**Comment by PCWin12** [comment]
Was anyone able to find the solution?

**Comment by JohnnyB90** [comment]
I believe that eftdb is blocking scraping attempts now. I made modifications to the code to try and fix it but then it started returning garbage encoded trash on purpose like this:
HTML content: �`o#R�z�,�&�►PG��↓8��:���Z⌂����"�{n�☻��9x~�zEQX����
�Il%`b�\KH��☺���.�r�Ք[n�n��(��6i���§§►☺q�q����→�↔!I�n,c��>�∟0◄Wpˑ����◄◄1_C}���☼��C?↔g���~#��aՓ�]�t�%☼+��#~��d��P�����{u�vQ�#�6�O'‼▼��{���E6C¶}'���o�
$]6�6P⌂����v�Z���؏����W⌂�ǃ�����Pk���o�����^��,��_�9▼�E��o�Ru^�7⌂|����Ŀ↓��N��ܨߖ��Z}7▼�8=�k�偖ޮ����B�L�v��!��� ү�/�ʹ��i^d[�.
